import { Case } from "../types";

export const mockCases: Case[] = [
  {
    id: "1",
    client_name: "Carlos Cox",
    doa: "2024-03-15",
    medical_status: "Ready for Assignment",
    client_status: "Active",
    law_firm: "XYZ Law",
  },
  {
    id: "2",
    client_name: "Maria Rodriguez",
    doa: "2024-03-10",
    medical_status: "Signed",
    client_status: "Active",
    law_firm: "XYZ Law",
  },
  {
    id: "3",
    client_name: "John Smith",
    doa: "2024-03-08",
    medical_status: "Scheduled",
    client_status: "Pending",
    law_firm: "ABC Legal",
  },
  {
    id: "4",
    client_name: "Emma Wilson",
    doa: "2024-03-05",
    medical_status: "Scheduled",
    client_status: "Pending",
    law_firm: "XYZ Law",
  },
  {
    id: "5",
    client_name: "Michael Chang",
    doa: "2024-03-03",
    medical_status: "Scheduled",
    client_status: "Pending",
    law_firm: "ABC Legal",
  },
  {
    id: "6",
    client_name: "Sarah Johnson",
    doa: "2024-03-01",
    medical_status: "Scheduled",
    client_status: "In Progress",
    law_firm: "XYZ Law",
  },
  {
    id: "7",
    client_name: "David Lee",
    doa: "2024-02-28",
    medical_status: "Signed",
    client_status: "Active",
    law_firm: "ABC Legal",
  },
  {
    id: "8",
    client_name: "Lisa Anderson",
    doa: "2024-02-25",
    medical_status: "Signed",
    client_status: "In Progress",
    law_firm: "XYZ Law",
  },
  {
    id: "9",
    client_name: "James Wilson",
    doa: "2024-02-23",
    medical_status: "Signed",
    client_status: "Active",
    law_firm: "ABC Legal",
  },
  {
    id: "10",
    client_name: "Patricia Martinez",
    doa: "2024-02-20",
    medical_status: "Scheduled",
    client_status: "In Progress",
    law_firm: "XYZ Law",
  },
  {
    id: "11",
    client_name: "Robert Taylor",
    doa: "2024-02-18",
    medical_status: "Scheduled",
    client_status: "Pending",
    law_firm: "ABC Legal",
  },
  {
    id: "12",
    client_name: "Jennifer Brown",
    doa: "2024-02-15",
    medical_status: "Signed",
    client_status: "Active",
    law_firm: "XYZ Law",
  },
  {
    id: "13",
    client_name: "William Davis",
    doa: "2024-02-13",
    medical_status: "Scheduled",
    client_status: "Pending",
    law_firm: "ABC Legal",
  },
  {
    id: "14",
    client_name: "Elizabeth Garcia",
    doa: "2024-02-10",
    medical_status: "Signed",
    client_status: "In Progress",
    law_firm: "XYZ Law",
  },
  {
    id: "15",
    client_name: "Thomas Moore",
    doa: "2024-02-08",
    medical_status: "Signed",
    client_status: "Pending",
    law_firm: "ABC Legal",
  },
  {
    id: "16",
    client_name: "Sandra White",
    doa: "2024-02-05",
    medical_status: "Ready for Assignment",
    client_status: "Active",
    law_firm: "XYZ Law",
  },
];
