import { Case } from "@cases/types";

export const mockCases: Case[] = [
  {
    id: "1",
    client_name: "Carlos Cox",
    doa: "2024-03-15",
    medical_status: "Ready for Assignment",
    client_status: "Active",
    law_firm: "XYZ Law",
  },
  {
    id: "2",
    client_name: "Maria Rodriguez",
    doa: "2024-03-10",
    medical_status: "Signed",
    client_status: "Active",
    law_firm: "XYZ Law",
  },
  {
    id: "3",
    client_name: "John Smith",
    doa: "2024-03-08",
    medical_status: "Scheduled",
    client_status: "Pending",
    law_firm: "ABC Legal",
  },
  {
    id: "4",
    client_name: "Emma Wilson",
    doa: "2024-03-05",
    medical_status: "Scheduled",
    client_status: "Pending",
    law_firm: "XYZ Law",
  },
  {
    id: "5",
    client_name: "Michael Chang",
    doa: "2024-03-03",
    medical_status: "Scheduled",
    client_status: "Pending",
    law_firm: "ABC Legal",
  },
  {
    id: "6",
    client_name: "Sarah Johnson",
    doa: "2024-03-01",
    medical_status: "Scheduled",
    client_status: "In Progress",
    law_firm: "XYZ Law",
  },
  {
    id: "7",
    client_name: "David Lee",
    doa: "2024-02-28",
    medical_status: "Signed",
    client_status: "Active",
    law_firm: "ABC Legal",
  },
  {
    id: "8",
    client_name: "Lisa Anderson",
    doa: "2024-02-25",
    medical_status: "Signed",
    client_status: "In Progress",
    law_firm: "XYZ Law",
  },
  {
    id: "9",
    client_name: "James Wilson",
    doa: "2024-02-23",
    medical_status: "Signed",
    client_status: "Active",
    law_firm: "ABC Legal",
  },
  {
    id: "10",
    client_name: "Patricia Martinez",
    doa: "2024-02-20",
    medical_status: "Scheduled",
    client_status: "In Progress",
    law_firm: "XYZ Law",
  },
  {
    id: "11",
    client_name: "Robert Taylor",
    doa: "2024-02-18",
    medical_status: "Scheduled",
    client_status: "Pending",
    law_firm: "ABC Legal",
  },
  {
    id: "12",
    client_name: "Jennifer Brown",
    doa: "2024-02-15",
    medical_status: "Signed",
    client_status: "Active",
    law_firm: "XYZ Law",
  },
  {
    id: "13",
    client_name: "William Davis",
    doa: "2024-02-13",
    medical_status: "Scheduled",
    client_status: "Pending",
    law_firm: "ABC Legal",
  },
  {
    id: "14",
    client_name: "Elizabeth Garcia",
    doa: "2024-02-10",
    medical_status: "Signed",
    client_status: "In Progress",
    law_firm: "XYZ Law",
  },
  {
    id: "15",
    client_name: "Thomas Moore",
    doa: "2024-02-08",
    medical_status: "Signed",
    client_status: "Pending",
    law_firm: "ABC Legal",
  },
  {
    id: "16",
    client_name: "Sandra White",
    doa: "2024-02-05",
    medical_status: "Ready for Assignment",
    client_status: "Active",
    law_firm: "XYZ Law",
  },
  {
    id: "17",
    client_name: "Christopher Clark",
    doa: "2024-02-03",
    medical_status: "Scheduled",
    client_status: "Active",
    law_firm: "ABC Legal",
  },
  {
    id: "18",
    client_name: "Nancy Hall",
    doa: "2024-02-01",
    medical_status: "Signed",
    client_status: "In Progress",
    law_firm: "XYZ Law",
  },
  {
    id: "19",
    client_name: "Daniel Young",
    doa: "2024-01-30",
    medical_status: "Ready for Assignment",
    client_status: "Pending",
    law_firm: "ABC Legal",
  },
  {
    id: "20",
    client_name: "Karen King",
    doa: "2024-01-28",
    medical_status: "Scheduled",
    client_status: "Active",
    law_firm: "XYZ Law",
  },
  {
    id: "21",
    client_name: "Matthew Wright",
    doa: "2024-01-25",
    medical_status: "Signed",
    client_status: "In Progress",
    law_firm: "ABC Legal",
  },
  {
    id: "22",
    client_name: "Betty Scott",
    doa: "2024-01-23",
    medical_status: "Scheduled",
    client_status: "Pending",
    law_firm: "XYZ Law",
  },
  {
    id: "23",
    client_name: "Anthony Green",
    doa: "2024-01-20",
    medical_status: "Ready for Assignment",
    client_status: "Active",
    law_firm: "ABC Legal",
  },
  {
    id: "24",
    client_name: "Helen Adams",
    doa: "2024-01-18",
    medical_status: "Signed",
    client_status: "In Progress",
    law_firm: "XYZ Law",
  },
  {
    id: "25",
    client_name: "Mark Baker",
    doa: "2024-01-15",
    medical_status: "Scheduled",
    client_status: "Pending",
    law_firm: "ABC Legal",
  },
  {
    id: "26",
    client_name: "Donna Nelson",
    doa: "2024-01-13",
    medical_status: "Signed",
    client_status: "Active",
    law_firm: "XYZ Law",
  },
  {
    id: "27",
    client_name: "Paul Carter",
    doa: "2024-01-10",
    medical_status: "Ready for Assignment",
    client_status: "In Progress",
    law_firm: "ABC Legal",
  },
  {
    id: "28",
    client_name: "Carol Mitchell",
    doa: "2024-01-08",
    medical_status: "Scheduled",
    client_status: "Pending",
    law_firm: "XYZ Law",
  },
  {
    id: "29",
    client_name: "Steven Perez",
    doa: "2024-01-05",
    medical_status: "Signed",
    client_status: "Active",
    law_firm: "ABC Legal",
  },
  {
    id: "30",
    client_name: "Ruth Roberts",
    doa: "2024-01-03",
    medical_status: "Scheduled",
    client_status: "In Progress",
    law_firm: "XYZ Law",
  },
  {
    id: "31",
    client_name: "Andrew Turner",
    doa: "2024-01-01",
    medical_status: "Ready for Assignment",
    client_status: "Pending",
    law_firm: "ABC Legal",
  },
  {
    id: "32",
    client_name: "Sharon Phillips",
    doa: "2023-12-30",
    medical_status: "Signed",
    client_status: "Active",
    law_firm: "XYZ Law",
  },
  {
    id: "33",
    client_name: "Kenneth Campbell",
    doa: "2023-12-28",
    medical_status: "Scheduled",
    client_status: "In Progress",
    law_firm: "ABC Legal",
  },
  {
    id: "34",
    client_name: "Deborah Parker",
    doa: "2023-12-25",
    medical_status: "Signed",
    client_status: "Pending",
    law_firm: "XYZ Law",
  },
  {
    id: "35",
    client_name: "Joshua Evans",
    doa: "2023-12-23",
    medical_status: "Ready for Assignment",
    client_status: "Active",
    law_firm: "ABC Legal",
  },
  {
    id: "36",
    client_name: "Michelle Edwards",
    doa: "2023-12-20",
    medical_status: "Scheduled",
    client_status: "In Progress",
    law_firm: "XYZ Law",
  },
  {
    id: "37",
    client_name: "Kevin Collins",
    doa: "2023-12-18",
    medical_status: "Signed",
    client_status: "Pending",
    law_firm: "ABC Legal",
  },
  {
    id: "38",
    client_name: "Laura Stewart",
    doa: "2023-12-15",
    medical_status: "Scheduled",
    client_status: "Active",
    law_firm: "XYZ Law",
  },
  {
    id: "39",
    client_name: "Brian Sanchez",
    doa: "2023-12-13",
    medical_status: "Ready for Assignment",
    client_status: "In Progress",
    law_firm: "ABC Legal",
  },
  {
    id: "40",
    client_name: "Amanda Morris",
    doa: "2023-12-10",
    medical_status: "Signed",
    client_status: "Pending",
    law_firm: "XYZ Law",
  },
  {
    id: "41",
    client_name: "George Rogers",
    doa: "2023-12-08",
    medical_status: "Scheduled",
    client_status: "Active",
    law_firm: "ABC Legal",
  },
  {
    id: "42",
    client_name: "Melissa Reed",
    doa: "2023-12-05",
    medical_status: "Signed",
    client_status: "In Progress",
    law_firm: "XYZ Law",
  },
  {
    id: "43",
    client_name: "Timothy Cook",
    doa: "2023-12-03",
    medical_status: "Ready for Assignment",
    client_status: "Pending",
    law_firm: "ABC Legal",
  },
  {
    id: "44",
    client_name: "Cynthia Morgan",
    doa: "2023-12-01",
    medical_status: "Scheduled",
    client_status: "Active",
    law_firm: "XYZ Law",
  },
  {
    id: "45",
    client_name: "Ronald Bell",
    doa: "2023-11-30",
    medical_status: "Signed",
    client_status: "In Progress",
    law_firm: "ABC Legal",
  },
  {
    id: "46",
    client_name: "Angela Murphy",
    doa: "2023-11-28",
    medical_status: "Scheduled",
    client_status: "Pending",
    law_firm: "XYZ Law",
  },
  {
    id: "47",
    client_name: "Jason Rivera",
    doa: "2023-11-25",
    medical_status: "Ready for Assignment",
    client_status: "Active",
    law_firm: "ABC Legal",
  },
  {
    id: "48",
    client_name: "Brenda Cooper",
    doa: "2023-11-23",
    medical_status: "Signed",
    client_status: "In Progress",
    law_firm: "XYZ Law",
  },
  {
    id: "49",
    client_name: "Jeffrey Richardson",
    doa: "2023-11-20",
    medical_status: "Scheduled",
    client_status: "Pending",
    law_firm: "ABC Legal",
  },
];
